# styler: off
without_financial <- tibble::tribble(
                ~company_name, ~postcode, ~emission_profile,      ~benchmark, ~ep_product, ~tilt_sector, ~tilt_subsector, ~isic_4digit, ~isic_4digit_name, ~equal_weight, ~worst_case, ~best_case,
                      "bruno",    27568L,            "high",           "all",       "car",          "D",             "d",       "4100",               "d",     0.3333333,         0.5,          0,
                      "bruno",    27568L,            "high",           "all",     "steel",          "C",             "c",       "4100",               "c",     0.3333333,         0.5,          0,
                      "bruno",    27568L,          "medium",           "all",     "wheat",          "B",             "b",       "4100",               "b",     0.3333333,           0,          1,
                      "mauro",    39221L,            "high",           "all",     "steel",          "C",             "c",       "4100",               "c",           0.5,         0.5,        0.5,
                      "mauro",    39221L,            "high",           "all",   "machine",          "C",             "c",       "4100",               "c",           0.5,         0.5,        0.5,
                      "mirja",    34117L,            "high",           "all",   "tractor",          "D",             "d",       "4100",               "d",           0.5,         0.5,        0.5,
                      "mirja",    34117L,            "high",           "all",    "cattle",          "A",             "a",       "4100",               "a",           0.5,         0.5,        0.5,
                     "pasant",    80337L,            "high",           "all",   "tractor",          "D",             "d",       "4100",               "d",           0.5,           1,          0,
                     "pasant",    80337L,             "low",           "all",     "apple",          "A",             "a",       "4100",               "a",           0.5,           0,          1,
                      "peter",    88131L,            "high",           "all",    "banana",          "A",             "a",       "4100",               "a",           0.5,           1,          0,
                      "peter",    88131L,          "medium",           "all",     "wheat",          "B",             "b",       "4100",               "b",           0.5,           0,          1,
              "peter peasant",    53773L,            "high",           "all",       "car",          "D",             "d",       "4100",               "d",           0.5,         0.5,        0.5,
              "peter peasant",    53773L,            "high",           "all",       "car",          "D",             "d",       "4100",               "d",           0.5,         0.5,        0.5,
                     "tilman",    12043L,            "high",           "all",       "car",          "D",             "d",       "4100",               "d",     0.1666667,   0.3333333,          0,
                     "tilman",    12043L,            "high",           "all",   "tractor",          "D",             "d",       "4100",               "d",     0.1666667,   0.3333333,          0,
                     "tilman",    12043L,            "high",           "all",     "steel",          "C",             "c",       "4100",               "c",     0.1666667,   0.3333333,          0,
                     "tilman",    12043L,             "low",           "all",     "truck",          "D",             "d",       "4100",               "d",     0.1666667,           0,        0.5,
                     "tilman",    12043L,             "low",           "all",     "truck",          "D",             "d",       "4100",               "d",     0.1666667,           0,        0.5,
                     "tilman",    12043L,          "medium",           "all",      "iron",          "C",             "c",       "4100",               "c",     0.1666667,           0,          0,
                      "bruno",    27568L,            "high",      "isic_sec",       "car",          "D",             "d",       "4100",               "d",     0.3333333,         0.5,          0,
                      "bruno",    27568L,            "high",      "isic_sec",     "steel",          "C",             "c",       "4100",               "c",     0.3333333,         0.5,          0,
                      "bruno",    27568L,          "medium",      "isic_sec",     "wheat",          "B",             "b",       "4100",               "b",     0.3333333,           0,          1,
                      "mauro",    39221L,            "high",      "isic_sec",     "steel",          "C",             "c",       "4100",               "c",           0.5,         0.5,        0.5,
                      "mauro",    39221L,            "high",      "isic_sec",   "machine",          "C",             "c",       "4100",               "c",           0.5,         0.5,        0.5,
                      "mirja",    34117L,            "high",      "isic_sec",   "tractor",          "D",             "d",       "4100",               "d",           0.5,         0.5,        0.5,
                      "mirja",    34117L,            "high",      "isic_sec",    "cattle",          "A",             "a",       "4100",               "a",           0.5,         0.5,        0.5,
                     "pasant",    80337L,            "high",      "isic_sec",   "tractor",          "D",             "d",       "4100",               "d",           0.5,           1,          0,
                     "pasant",    80337L,             "low",      "isic_sec",     "apple",          "A",             "a",       "4100",               "a",           0.5,           0,          1,
                      "peter",    88131L,            "high",      "isic_sec",    "banana",          "A",             "a",       "4100",               "a",           0.5,           1,          0,
                      "peter",    88131L,          "medium",      "isic_sec",     "wheat",          "B",             "b",       "4100",               "b",           0.5,           0,          1,
              "peter peasant",    53773L,            "high",      "isic_sec",       "car",          "D",             "d",       "4100",               "d",           0.5,         0.5,        0.5,
              "peter peasant",    53773L,            "high",      "isic_sec",       "car",          "D",             "d",       "4100",               "d",           0.5,         0.5,        0.5,
                     "tilman",    12043L,            "high",      "isic_sec",       "car",          "D",             "d",       "4100",               "d",     0.1666667,   0.3333333,          0,
                     "tilman",    12043L,            "high",      "isic_sec",   "tractor",          "D",             "d",       "4100",               "d",     0.1666667,   0.3333333,          0,
                     "tilman",    12043L,            "high",      "isic_sec",     "steel",          "C",             "c",       "4100",               "c",     0.1666667,   0.3333333,          0,
                     "tilman",    12043L,             "low",      "isic_sec",     "truck",          "D",             "d",       "4100",               "d",     0.1666667,           0,        0.5,
                     "tilman",    12043L,             "low",      "isic_sec",     "truck",          "D",             "d",       "4100",               "d",     0.1666667,           0,        0.5,
                     "tilman",    12043L,          "medium",      "isic_sec",      "iron",          "C",             "c",       "4100",               "c",     0.1666667,           0,          0,
                      "bruno",    27568L,            "high",      "tilt_sec",       "car",          "D",             "d",       "4100",               "d",     0.3333333,         0.5,          0,
                      "bruno",    27568L,            "high",      "tilt_sec",     "steel",          "C",             "c",       "4100",               "c",     0.3333333,         0.5,          0,
                      "bruno",    27568L,          "medium",      "tilt_sec",     "wheat",          "B",             "b",       "4100",               "b",     0.3333333,           0,          1,
                      "mauro",    39221L,            "high",      "tilt_sec",     "steel",          "C",             "c",       "4100",               "c",           0.5,         0.5,        0.5,
                      "mauro",    39221L,            "high",      "tilt_sec",   "machine",          "C",             "c",       "4100",               "c",           0.5,         0.5,        0.5,
                      "mirja",    34117L,            "high",      "tilt_sec",   "tractor",          "D",             "d",       "4100",               "d",           0.5,         0.5,        0.5,
                      "mirja",    34117L,            "high",      "tilt_sec",    "cattle",          "A",             "a",       "4100",               "a",           0.5,         0.5,        0.5,
                     "pasant",    80337L,            "high",      "tilt_sec",   "tractor",          "D",             "d",       "4100",               "d",           0.5,           1,          0,
                     "pasant",    80337L,             "low",      "tilt_sec",     "apple",          "A",             "a",       "4100",               "a",           0.5,           0,          1,
                      "peter",    88131L,            "high",      "tilt_sec",    "banana",          "A",             "a",       "4100",               "a",           0.5,           1,          0,
                      "peter",    88131L,          "medium",      "tilt_sec",     "wheat",          "B",             "b",       "4100",               "b",           0.5,           0,          1,
              "peter peasant",    53773L,            "high",      "tilt_sec",       "car",          "D",             "d",       "4100",               "d",           0.5,         0.5,        0.5,
              "peter peasant",    53773L,            "high",      "tilt_sec",       "car",          "D",             "d",       "4100",               "d",           0.5,         0.5,        0.5,
                     "tilman",    12043L,            "high",      "tilt_sec",       "car",          "D",             "d",       "4100",               "d",     0.1666667,   0.3333333,          0,
                     "tilman",    12043L,            "high",      "tilt_sec",   "tractor",          "D",             "d",       "4100",               "d",     0.1666667,   0.3333333,          0,
                     "tilman",    12043L,            "high",      "tilt_sec",     "steel",          "C",             "c",       "4100",               "c",     0.1666667,   0.3333333,          0,
                     "tilman",    12043L,             "low",      "tilt_sec",     "truck",          "D",             "d",       "4100",               "d",     0.1666667,           0,        0.5,
                     "tilman",    12043L,             "low",      "tilt_sec",     "truck",          "D",             "d",       "4100",               "d",     0.1666667,           0,        0.5,
                     "tilman",    12043L,          "medium",      "tilt_sec",      "iron",          "C",             "c",       "4100",               "c",     0.1666667,           0,          0,
                      "bruno",    27568L,            "high",          "unit",       "car",          "D",             "d",       "4100",               "d",     0.3333333,         0.5,          0,
                      "bruno",    27568L,            "high",          "unit",     "steel",          "C",             "c",       "4100",               "c",     0.3333333,         0.5,          0,
                      "bruno",    27568L,          "medium",          "unit",     "wheat",          "B",             "b",       "4100",               "b",     0.3333333,           0,          1,
                      "mauro",    39221L,            "high",          "unit",     "steel",          "C",             "c",       "4100",               "c",           0.5,         0.5,        0.5,
                      "mauro",    39221L,            "high",          "unit",   "machine",          "C",             "c",       "4100",               "c",           0.5,         0.5,        0.5,
                      "mirja",    34117L,            "high",          "unit",   "tractor",          "D",             "d",       "4100",               "d",           0.5,         0.5,        0.5,
                      "mirja",    34117L,            "high",          "unit",    "cattle",          "A",             "a",       "4100",               "a",           0.5,         0.5,        0.5,
                     "pasant",    80337L,            "high",          "unit",   "tractor",          "D",             "d",       "4100",               "d",           0.5,           1,          0,
                     "pasant",    80337L,             "low",          "unit",     "apple",          "A",             "a",       "4100",               "a",           0.5,           0,          1,
                      "peter",    88131L,            "high",          "unit",    "banana",          "A",             "a",       "4100",               "a",           0.5,           1,          0,
                      "peter",    88131L,          "medium",          "unit",     "wheat",          "B",             "b",       "4100",               "b",           0.5,           0,          1,
              "peter peasant",    53773L,            "high",          "unit",       "car",          "D",             "d",       "4100",               "d",           0.5,         0.5,        0.5,
              "peter peasant",    53773L,            "high",          "unit",       "car",          "D",             "d",       "4100",               "d",           0.5,         0.5,        0.5,
                     "tilman",    12043L,            "high",          "unit",       "car",          "D",             "d",       "4100",               "d",     0.1666667,   0.3333333,          0,
                     "tilman",    12043L,            "high",          "unit",   "tractor",          "D",             "d",       "4100",               "d",     0.1666667,   0.3333333,          0,
                     "tilman",    12043L,            "high",          "unit",     "steel",          "C",             "c",       "4100",               "c",     0.1666667,   0.3333333,          0,
                     "tilman",    12043L,             "low",          "unit",     "truck",          "D",             "d",       "4100",               "d",     0.1666667,           0,        0.5,
                     "tilman",    12043L,             "low",          "unit",     "truck",          "D",             "d",       "4100",               "d",     0.1666667,           0,        0.5,
                     "tilman",    12043L,          "medium",          "unit",      "iron",          "C",             "c",       "4100",               "c",     0.1666667,           0,          0,
                      "bruno",    27568L,            "high", "unit_isic_sec",       "car",          "D",             "d",       "4100",               "d",     0.3333333,         0.5,          0,
                      "bruno",    27568L,            "high", "unit_isic_sec",     "steel",          "C",             "c",       "4100",               "c",     0.3333333,         0.5,          0,
                      "bruno",    27568L,          "medium", "unit_isic_sec",     "wheat",          "B",             "b",       "4100",               "b",     0.3333333,           0,          1,
                      "mauro",    39221L,            "high", "unit_isic_sec",     "steel",          "C",             "c",       "4100",               "c",           0.5,         0.5,        0.5,
                      "mauro",    39221L,            "high", "unit_isic_sec",   "machine",          "C",             "c",       "4100",               "c",           0.5,         0.5,        0.5,
                      "mirja",    34117L,            "high", "unit_isic_sec",   "tractor",          "D",             "d",       "4100",               "d",           0.5,         0.5,        0.5,
                      "mirja",    34117L,            "high", "unit_isic_sec",    "cattle",          "A",             "a",       "4100",               "a",           0.5,         0.5,        0.5,
                     "pasant",    80337L,            "high", "unit_isic_sec",   "tractor",          "D",             "d",       "4100",               "d",           0.5,           1,          0,
                     "pasant",    80337L,             "low", "unit_isic_sec",     "apple",          "A",             "a",       "4100",               "a",           0.5,           0,          1,
                      "peter",    88131L,            "high", "unit_isic_sec",    "banana",          "A",             "a",       "4100",               "a",           0.5,           1,          0,
                      "peter",    88131L,          "medium", "unit_isic_sec",     "wheat",          "B",             "b",       "4100",               "b",           0.5,           0,          1,
              "peter peasant",    53773L,            "high", "unit_isic_sec",       "car",          "D",             "d",       "4100",               "d",           0.5,         0.5,        0.5,
              "peter peasant",    53773L,            "high", "unit_isic_sec",       "car",          "D",             "d",       "4100",               "d",           0.5,         0.5,        0.5,
                     "tilman",    12043L,            "high", "unit_isic_sec",       "car",          "D",             "d",       "4100",               "d",     0.1666667,   0.3333333,          0,
                     "tilman",    12043L,            "high", "unit_isic_sec",   "tractor",          "D",             "d",       "4100",               "d",     0.1666667,   0.3333333,          0,
                     "tilman",    12043L,            "high", "unit_isic_sec",     "steel",          "C",             "c",       "4100",               "c",     0.1666667,   0.3333333,          0,
                     "tilman",    12043L,             "low", "unit_isic_sec",     "truck",          "D",             "d",       "4100",               "d",     0.1666667,           0,        0.5,
                     "tilman",    12043L,             "low", "unit_isic_sec",     "truck",          "D",             "d",       "4100",               "d",     0.1666667,           0,        0.5,
                     "tilman",    12043L,          "medium", "unit_isic_sec",      "iron",          "C",             "c",       "4100",               "c",     0.1666667,           0,          0,
                      "bruno",    27568L,            "high", "unit_tilt_sec",       "car",          "D",             "d",       "4100",               "d",     0.3333333,         0.5,          0,
                      "bruno",    27568L,            "high", "unit_tilt_sec",     "steel",          "C",             "c",       "4100",               "c",     0.3333333,         0.5,          0,
                      "bruno",    27568L,          "medium", "unit_tilt_sec",     "wheat",          "B",             "b",       "4100",               "b",     0.3333333,           0,          1,
                      "mauro",    39221L,            "high", "unit_tilt_sec",     "steel",          "C",             "c",       "4100",               "c",           0.5,         0.5,        0.5,
                      "mauro",    39221L,            "high", "unit_tilt_sec",   "machine",          "C",             "c",       "4100",               "c",           0.5,         0.5,        0.5,
                      "mirja",    34117L,            "high", "unit_tilt_sec",   "tractor",          "D",             "d",       "4100",               "d",           0.5,         0.5,        0.5,
                      "mirja",    34117L,            "high", "unit_tilt_sec",    "cattle",          "A",             "a",       "4100",               "a",           0.5,         0.5,        0.5,
                     "pasant",    80337L,            "high", "unit_tilt_sec",   "tractor",          "D",             "d",       "4100",               "d",           0.5,           1,          0,
                     "pasant",    80337L,             "low", "unit_tilt_sec",     "apple",          "A",             "a",       "4100",               "a",           0.5,           0,          1,
                      "peter",    88131L,            "high", "unit_tilt_sec",    "banana",          "A",             "a",       "4100",               "a",           0.5,           1,          0,
                      "peter",    88131L,          "medium", "unit_tilt_sec",     "wheat",          "B",             "b",       "4100",               "b",           0.5,           0,          1,
              "peter peasant",    53773L,            "high", "unit_tilt_sec",       "car",          "D",             "d",       "4100",               "d",           0.5,         0.5,        0.5,
              "peter peasant",    53773L,            "high", "unit_tilt_sec",       "car",          "D",             "d",       "4100",               "d",           0.5,         0.5,        0.5,
                     "tilman",    12043L,            "high", "unit_tilt_sec",       "car",          "D",             "d",       "4100",               "d",     0.1666667,   0.3333333,          0,
                     "tilman",    12043L,            "high", "unit_tilt_sec",   "tractor",          "D",             "d",       "4100",               "d",     0.1666667,   0.3333333,          0,
                     "tilman",    12043L,            "high", "unit_tilt_sec",     "steel",          "C",             "c",       "4100",               "c",     0.1666667,   0.3333333,          0,
                     "tilman",    12043L,             "low", "unit_tilt_sec",     "truck",          "D",             "d",       "4100",               "d",     0.1666667,           0,        0.5,
                     "tilman",    12043L,             "low", "unit_tilt_sec",     "truck",          "D",             "d",       "4100",               "d",     0.1666667,           0,        0.5,
                     "tilman",    12043L,          "medium", "unit_tilt_sec",      "iron",          "C",             "c",       "4100",               "c",     0.1666667,           0,          0
              )
# styler: on

usethis::use_data(without_financial, overwrite = TRUE)
