# styler: off
without_financial <- tibble::tribble(
                ~company_name, ~xctr_risk_category,      ~benchmark, ~product_name, ~tilt_sector,
              "peter peasant",              "high",           "all",         "car",          "D",
              "peter peasant",              "high",          "unit",         "car",          "D",
              "peter peasant",            "medium",      "tilt_sec",         "car",          "D",
              "peter peasant",            "medium", "unit_tilt_sec",         "car",          "D",
              "peter peasant",               "low",      "isic_sec",         "car",          "D",
              "peter peasant",               "low", "unit_isic_sec",         "car",          "D",
                      "peter",              "high",           "all",      "banana",          "A",
                      "peter",              "high",          "unit",      "banana",          "A",
                      "peter",            "medium",      "tilt_sec",      "banana",          "A",
                      "peter",            "medium", "unit_tilt_sec",      "banana",          "A",
                      "peter",              "high",      "isic_sec",      "banana",          "A",
                      "peter",               "low", "unit_isic_sec",      "banana",          "A",
                     "pasant",              "high",           "all",     "tractor",          "D",
                      "peter",              "high",          "unit",       "wheat",          "B",
                      "peter",            "medium",      "tilt_sec",       "wheat",          "B",
                      "peter",            "medium", "unit_tilt_sec",       "wheat",          "B",
                      "peter",               "low",      "isic_sec",       "wheat",          "B",
                      "peter",               "low", "unit_isic_sec",       "wheat",          "B",
                      "mauro",              "high",           "all",       "steel",          "C",
                     "pasant",            "medium",          "unit",       "apple",          "A",
                     "pasant",            "medium",      "tilt_sec",       "apple",          "A",
                     "pasant",            "medium", "unit_tilt_sec",       "apple",          "A",
                     "pasant",               "low",      "isic_sec",       "apple",          "A",
                     "pasant",               "low", "unit_isic_sec",       "apple",          "A",
                      "mauro",              "high",           "all",     "machine",          "C",
                     "pasant",            "medium",          "unit",     "tractor",          "D",
                     "pasant",            "medium",      "tilt_sec",     "tractor",          "D",
                     "pasant",              "high", "unit_tilt_sec",     "tractor",          "D",
                     "pasant",               "low",      "isic_sec",     "tractor",          "D",
                     "pasant",               "low", "unit_isic_sec",     "tractor",          "D",
                      "mirja",              "high",           "all",     "tractor",          "D",
                      "mauro",            "medium",          "unit",       "steel",          "C",
                      "mauro",              "high",      "tilt_sec",       "steel",          "C",
                      "mauro",              "high", "unit_tilt_sec",       "steel",          "C",
                      "mauro",               "low",      "isic_sec",       "steel",          "C",
                      "mauro",              "high", "unit_isic_sec",       "steel",          "C",
                      "mirja",              "high",           "all",      "cattle",          "A",
                      "mauro",            "medium",          "unit",     "machine",          "C",
                      "mauro",              "high",      "tilt_sec",     "machine",          "C",
                      "mauro",              "high", "unit_tilt_sec",     "machine",          "C",
                      "mauro",               "low",      "isic_sec",     "machine",          "C",
                      "mauro",              "high", "unit_isic_sec",     "machine",          "C",
                      "bruno",              "high",           "all",         "car",          "D",
                      "mirja",            "medium",          "unit",     "tractor",          "D",
                      "mirja",              "high",      "tilt_sec",     "tractor",          "D",
                      "mirja",              "high", "unit_tilt_sec",     "tractor",          "D",
                      "mirja",            "medium",      "isic_sec",     "tractor",          "D",
                      "mirja",              "high", "unit_isic_sec",     "tractor",          "D",
                      "bruno",              "high",           "all",       "steel",          "C",
                      "mirja",            "medium",          "unit",      "cattle",          "A",
                      "mirja",              "high",      "tilt_sec",      "cattle",          "A",
                      "mirja",              "high", "unit_tilt_sec",      "cattle",          "A",
                      "mirja",            "medium",      "isic_sec",      "cattle",          "A",
                      "mirja",              "high", "unit_isic_sec",      "cattle",          "A",
                     "tilman",              "high",           "all",         "car",          "D",
                      "bruno",            "medium",          "unit",      "banana",          "B",
                      "bruno",              "high",      "tilt_sec",      "banana",          "B",
                      "bruno",              "high", "unit_tilt_sec",      "banana",          "B"
              )
# styler: on

usethis::use_data(without_financial, overwrite = TRUE)
