#' @keywords internal
"_PACKAGE"

## usethis namespace: start
#' @importFrom dplyr arrange
#' @importFrom dplyr bind_rows
#' @importFrom dplyr case_when
#' @importFrom dplyr distinct
#' @importFrom dplyr filter
#' @importFrom dplyr first
#' @importFrom dplyr group_by
#' @importFrom dplyr inner_join
#' @importFrom dplyr left_join
#' @importFrom dplyr mutate
#' @importFrom dplyr n
#' @importFrom dplyr pull
#' @importFrom dplyr select
#' @importFrom dplyr summarise
#' @importFrom dplyr summarize
#' @importFrom dplyr ungroup
#' @importFrom eurostat get_eurostat_geospatial
#' @importFrom ggalluvial geom_alluvium
#' @importFrom ggalluvial geom_stratum
#' @importFrom ggalluvial StatStratum
#' @importFrom ggplot2 aes
#' @importFrom ggplot2 after_stat
#' @importFrom ggplot2 coord_sf
#' @importFrom ggplot2 element_blank
#' @importFrom ggplot2 element_text
#' @importFrom ggplot2 facet_grid
#' @importFrom ggplot2 facet_wrap
#' @importFrom ggplot2 geom_bar
#' @importFrom ggplot2 geom_col
#' @importFrom ggplot2 geom_label
#' @importFrom ggplot2 geom_point
#' @importFrom ggplot2 geom_sf
#' @importFrom ggplot2 geom_text
#' @importFrom ggplot2 ggplot
#' @importFrom ggplot2 ggplot_build
#' @importFrom ggplot2 ggtitle
#' @importFrom ggplot2 labs
#' @importFrom ggplot2 position_stack
#' @importFrom ggplot2 scale_fill_manual
#' @importFrom ggplot2 scale_shape_manual
#' @importFrom ggplot2 scale_x_discrete
#' @importFrom ggplot2 sym
#' @importFrom ggplot2 theme
#' @importFrom ggplot2 theme_classic
#' @importFrom ggplot2 theme_minimal
#' @importFrom ggplot2 unit
#' @importFrom ggplot2 xlim
#' @importFrom ggplot2 ylab
#' @importFrom ggplot2 ylim
#' @importFrom ggpubr ggarrange
#' @importFrom giscoR gisco_get_nuts
#' @importFrom glue glue
#' @importFrom grDevices col2rgb
#' @importFrom grDevices rgb
#' @importFrom here here
#' @importFrom purrr pmap
#' @importFrom readr read_csv2
#' @importFrom rlang :=
#' @importFrom rlang .data
#' @importFrom rlang .env
#' @importFrom rlang arg_match
#' @importFrom sf st_as_sf
#' @importFrom showtext showtext_auto
#' @importFrom stats ave
#' @importFrom stats na.omit
#' @importFrom sysfonts font_add_google
#' @importFrom tibble as_tibble
#' @importFrom tibble is_tibble
#' @importFrom tibble tibble
#' @importFrom tibble tribble
#' @importFrom tidyr drop_na
#' @importFrom tidyr pivot_wider
#' @importFrom tidyselect matches
#' @importFrom tiltIndicator example_data_factory
#' @importFrom tiltIndicatorAfter profile_emissions
#' @importFrom tools toTitleCase
#' @importFrom vroom col_character
#' @importFrom vroom col_integer
#' @importFrom vroom cols
## usethis namespace: end
NULL
